[package]
name = "vamatohd/morph"
description = "TweenService wrapper"
license = "MIT"
authors = ["Vamato"]

version = "0.0.2"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]
